version: '3.8'

services:
  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: visitors
      MYSQL_USER: une
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
